/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapServicesDotxmlRouteImport } from './routes/sitemap-services[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ArchitectsRouteImport } from './routes/architects'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as DebugImagesRouteImport } from './routes/debug.images'
import { Route as ApiPublicAnalyticsRouteImport } from './routes/api/public/analytics'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapServicesDotxmlRoute = SitemapServicesDotxmlRouteImport.update({
  id: '/sitemap-services.xml',
  path: '/sitemap-services.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectsRoute = ArchitectsRouteImport.update({
  id: '/architects',
  path: '/architects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const DebugImagesRoute = DebugImagesRouteImport.update({
  id: '/debug/images',
  path: '/debug/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyticsRoute = ApiPublicAnalyticsRouteImport.update({
  id: '/api/public/analytics',
  path: '/api/public/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/architects': typeof ArchitectsRoute
  '/export': typeof ExportRoute
  '/procurement': typeof ProcurementRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-services.xml': typeof SitemapServicesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/debug/images': typeof DebugImagesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$id': typeof ServicesIdRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/architects': typeof ArchitectsRoute
  '/export': typeof ExportRoute
  '/procurement': typeof ProcurementRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-services.xml': typeof SitemapServicesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/debug/images': typeof DebugImagesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$id': typeof ServicesIdRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/architects': typeof ArchitectsRoute
  '/export': typeof ExportRoute
  '/procurement': typeof ProcurementRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-services.xml': typeof SitemapServicesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/debug/images': typeof DebugImagesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$id': typeof ServicesIdRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/architects'
    | '/export'
    | '/procurement'
    | '/projects'
    | '/robots.txt'
    | '/sitemap-services.xml'
    | '/sitemap.xml'
    | '/debug/images'
    | '/projects/$slug'
    | '/services/$id'
    | '/api/public/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/architects'
    | '/export'
    | '/procurement'
    | '/projects'
    | '/robots.txt'
    | '/sitemap-services.xml'
    | '/sitemap.xml'
    | '/debug/images'
    | '/projects/$slug'
    | '/services/$id'
    | '/api/public/analytics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/architects'
    | '/export'
    | '/procurement'
    | '/projects'
    | '/robots.txt'
    | '/sitemap-services.xml'
    | '/sitemap.xml'
    | '/debug/images'
    | '/projects/$slug'
    | '/services/$id'
    | '/api/public/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchitectsRoute: typeof ArchitectsRoute
  ExportRoute: typeof ExportRoute
  ProcurementRoute: typeof ProcurementRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapServicesDotxmlRoute: typeof SitemapServicesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DebugImagesRoute: typeof DebugImagesRoute
  ServicesIdRoute: typeof ServicesIdRoute
  ApiPublicAnalyticsRoute: typeof ApiPublicAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-services.xml': {
      id: '/sitemap-services.xml'
      path: '/sitemap-services.xml'
      fullPath: '/sitemap-services.xml'
      preLoaderRoute: typeof SitemapServicesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architects': {
      id: '/architects'
      path: '/architects'
      fullPath: '/architects'
      preLoaderRoute: typeof ArchitectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/debug/images': {
      id: '/debug/images'
      path: '/debug/images'
      fullPath: '/debug/images'
      preLoaderRoute: typeof DebugImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics': {
      id: '/api/public/analytics'
      path: '/api/public/analytics'
      fullPath: '/api/public/analytics'
      preLoaderRoute: typeof ApiPublicAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchitectsRoute: ArchitectsRoute,
  ExportRoute: ExportRoute,
  ProcurementRoute: ProcurementRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapServicesDotxmlRoute: SitemapServicesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DebugImagesRoute: DebugImagesRoute,
  ServicesIdRoute: ServicesIdRoute,
  ApiPublicAnalyticsRoute: ApiPublicAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
