/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ApiPublicAnalyticsRouteImport } from './routes/api/public/analytics'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const ApiPublicAnalyticsRoute = ApiPublicAnalyticsRouteImport.update({
  id: '/api/public/analytics',
  path: '/api/public/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$id': typeof ServicesIdRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$id': typeof ServicesIdRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$id': typeof ServicesIdRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/projects/$slug'
    | '/services/$id'
    | '/api/public/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/projects/$slug'
    | '/services/$id'
    | '/api/public/analytics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/projects/$slug'
    | '/services/$id'
    | '/api/public/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesIdRoute: typeof ServicesIdRoute
  ApiPublicAnalyticsRoute: typeof ApiPublicAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/api/public/analytics': {
      id: '/api/public/analytics'
      path: '/api/public/analytics'
      fullPath: '/api/public/analytics'
      preLoaderRoute: typeof ApiPublicAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesIdRoute: ServicesIdRoute,
  ApiPublicAnalyticsRoute: ApiPublicAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
